### ISSUE TITLE
第七章SVD方法求解ICP代码可能有疏漏

### ISSUE THREAD

**Issue by JimZhou-001** [gaoxiang12/slambook#106]
高博您好：

我最近用到了书中第七章3D-3D变换估计的函数，发现结果不对劲，于是参考了PCL源码中的SVD求解变换矩阵部分，发现它在计算完U、V之后有以下语句：

  if (u.determinant () * v.determinant () < 0)
  {
    for (int x = 0; x < 3; ++x)
      v (x, 2) *= -1;
  }

您的程序似乎没有这个判断过程。

不知是我的理解问题，还是您的疏漏？

期待您的解答！谢谢！

**Comment by gaoxiang12** [comment]
应该是我没有考虑这种情况，在下一版书中修正吧。
