### ISSUE TITLE
Conversion from pangolin::OpenGlMatrix to Eigen::Matrix

### ISSUE THREAD

**Issue by Jyang772** [gaoxiang12/slambook#13]
I am getting the following error when trying to build visualizeGeometry:
```
error: conversion from ‘pangolin::OpenGlMatrix’ to non-scalar type ‘Eigen::Matrix<double, 4, 4>’ requested
         Matrix<double,4,4> m = matrix;
```

**Comment by Jyang772** [comment]
Fixed.

`Matrix<double,4,4> m = ToEigen<double>(matrix);`

**Comment by jamboo2017** [comment]
It shows 
 error: ‘ToEigen’ was not declared in this scope
Any header files needed to use ToEigen()?
Thx

**Comment by hoastyle** [comment]
Add #define HAVE_EIGEN and pangolin::ToEigen to fix this.

**Comment by GoldExperience** [comment]
it gives error: ‘ToEigen’ is not a member of ‘pangolin’
when I use : Matrix<double,4,4> m =pangolin::ToEigen<double>(matrix);
and the same porblem as jamboo2017

**Comment by missdown** [comment]
The latest version has fix the bug.

**Comment by Lyoid** [comment]
you should install Eigen first.and then install pangolin.This way will help the pangolin add the function about Eigen.

**Comment by wheatjo** [comment]
use this:
        for(int i = 0; i<4; i++)
            for(int j = 0; j<4; j++)
                m(i,j) = matrix(i,j);

**Comment by wangman123** [comment]
Define the toeigen function yourself

**Comment by xuehu2** [comment]
> you should install Eigen first.and then install pangolin.This way will help the pangolin add the function about Eigen.

this is a true way to solve the question.
