### ISSUE TITLE
ch4 编译  useSophus 报错

### ISSUE THREAD

**Issue by WithFoxSquirrel** [gaoxiang12/slambook#143]
### 编译useSophus 报错
```
  /usr/local/include/sophus/common.hpp:44:10: error: 'auto' not allowed in function return type
    static auto test(int)
           ^~~~
  /usr/local/include/sophus/common.hpp:44:24: error: expected ';' at end of declaration list
    static auto test(int)

```
###  查资料有说是c++11的问题，cmakelists增加 set( CMAKE_CXX_FLAGS "-std=c++14 -O3" ) 后，编译报

```
   /Users/hans.hu/work/slam/slambook/ch4/useSophus/useSophus.cpp:16:13: error: use of class template 'Sophus::SO3' requires template arguments
       Sophus::SO3 SO3_R(R);               // Sophus::SO(3)可以直接从旋转矩阵构造
               ^
   /usr/local/include/sophus/so3.hpp:423:7: note: template is declared here
   class SO3 : public SO3Base<SO3<Scalar_, Options>> {
```

**Comment by gaoxiang12** [comment]
书里代码用的是早期非模板版本的sophus。在git clone sophus之后需要checkout到指定版本才能编译。

**Comment by roachsinai** [comment]
不知高博能否告知，你所使用的gcc版本？

**Comment by LvjianLu** [comment]
> ![snip20181019_12](https://user-images.githubusercontent.com/6671936/47217260-62e05380-d3da-11e8-9573-3258927af352.png)
> 
> > 按照书上，checkout到 git checkout a621ff (实际是a621ff2)
> 
> ![snip20181019_13](https://user-images.githubusercontent.com/6671936/47217359-b357b100-d3da-11e8-86ae-57d2b9841dcc.png)
> 
> > 编译出错，修改unit_complex_ real() = 1.0 ;   =>   unit_complex_.real(1.0); 编译成功
> 
> > 然后到ch4/useSophus/build 目录， make
> 
> ![snip20181022_14](https://user-images.githubusercontent.com/6671936/47274970-cab2bc00-d5dd-11e8-925d-0d38147b8685.png)
> 
> > clang 版本和平台 Apple LLVM version 9.1.0 (clang-902.0.39.2) , update_se3(0,0) = 1e-4d; -> update_se3(0,0) = 1e-4;
> 
> ![image](https://user-images.githubusercontent.com/6671936/47275082-de125700-d5de-11e8-9d77-9d9c0dfd155b.png)
> 
> > 高博，书上的有些例子不能在 osx 上编译吗？

分别改为：
unit_complex_.real(1.);
unit_complex_.imag(0.);
以及
update_se3(0,0) = 1e-4;
就可以编译通过

**Comment by BTREE-C802** [comment]
您好，我叫旷鸿章，我已经收到了你的邮件。谢谢！
