### ISSUE TITLE
Typo regarding Equation (4.26)

### ISSUE THREAD

**Issue by JustWon** [gaoxiang12/slambook#148]
Hello
I found typos on the equation (4.26).

![image](https://user-images.githubusercontent.com/14357526/48313983-89bf2d80-e606-11e8-909e-d1758697d43f.png)

(1) the minus sign at the back of theta^5 in the second line should be a plus sign since the plus and minus signs are alternatively shown.

(2) the minus sign at the back of a^ in the third line should be a plus sign so that we can derive the forth line from the third.

Regards,

**Comment by gaoxiang12** [comment]
yeah, thanks for pointing it out.
