### ISSUE TITLE
勘误（影响不大，只是希望完美）

### ISSUE THREAD

**Issue by sunkaianna** [gaoxiang12/slambook#15]
第九讲 实践：设计前端
p233，第一段第二行：“常见的做法时”应该是“常见的做法是”。

**Comment by gaoxiang12** [comment]
谢谢您，已收到。
附件是现在版本的勘误表。


Xiang Gao (高翔)
Ph. D. Student in Tsinghua University
Room 428, Main Building, Beijing, 100084
Tel: (+86)18811360537

**Comment by gaoxiang12** [comment]
[勘误_4.28.xlsx](https://github.com/gaoxiang12/slambook/files/998378/_4.28.xlsx)
