### ISSUE TITLE
g2o_viewer not found on Mac

### ISSUE THREAD

**Issue by RunJianChen** [gaoxiang12/slambook#166]
I install g2o in the 3rdParty on my mac but cannot find g2o_viewer.

Is there any solution to this problem?

Thanks a lot!

**Comment by gaoxiang12** [comment]
I have not tested it on mac. g2o_viewer needs libqlgviewer, you may search if grew supports it or compile it from source.

**Comment by RunJianChen** [comment]
Thanks a lot!

    I installed libqlgviewer previously and reinstalled g2o, but it didn't work.

    I will try more to fix it but maybe it is a problem on macOS,

    It's really nice of you and thank you again!



-----原始邮件-----
发件人:"Xiang Gao" <notifications@github.com>
发送时间:2018-12-07 16:11:53 (星期五)
收件人: gaoxiang12/slambook <slambook@noreply.github.com>
抄送: RunJianChen <3160103989@zju.edu.cn>, Author <author@noreply.github.com>
主题: Re: [gaoxiang12/slambook] g2o_viewer not found on Mac (#166)



I have not tested it on mac. g2o_viewer needs libqlgviewer, you may search if grew supports it or compile it from source.

**Comment by IvyGongoogle** [comment]
@RunJianChen  meet the same problem. How you solve it?

**Comment by RunJianChen** [comment]
@IvyGongoogle I thought there was no g2o_viewer for mac and gave up. But other parts worked well. If you need g2o_viewer, maybe you should turn to ubuntu. Thank you!
