### ISSUE TITLE
第7讲 ICP(一个小建议，不算勘误)

### ISSUE THREAD

**Issue by XiaoyuBIE1994** [gaoxiang12/slambook#171]
第7讲中用SVD法求解ICP的公式推导中，得到R = U * V'，但看参考文献的时候，推导出来应该是是R = V * U'。想了很久没想通，最奇怪的是代码里面用  U * V' 算出来的结果才是正确的，V * U'的结果就不对。最后发现是因为从公式(7.55)到(7.56)的时候，将 q' q T 换成了 q q' T，所以会得出 R =  U * V' 的结果。建议高博在第二版的时候改一改这个地方或者做个说明，避免有像我这样眼神不好的人看很久看不懂 /(ㄒoㄒ)/~~

**Comment by gaoxiang12** [comment]
啊好的，我记得还有个小问题是要判断奇异值的正负来着。

**Comment by XiaoyuBIE1994** [comment]
恩，按照文献里的意思，如果求出来的R的行列式为+1就是旋转矩阵，如果是-1的话，需要额外考虑
