### ISSUE TITLE
ch3中下载Pangolin库的时候，make的时候出现错误

### ISSUE THREAD

**Issue by liushuangliuliu** [gaoxiang12/slambook#175]
请问make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `src/libpangolin.so'.  Stop.
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
这个错误怎么解决阿？

**Comment by XiaoyuBIE1994** [comment]
我用的Ubuntu16.04直接编译并没有错呀，这边有个回答可能有用https://github.com/RobotLocomotion/drake/issues/2087#issue-148166827

**Comment by liushuangliuliu** [comment]
我用的是14我升级到16试试，谢谢啦

**Comment by gaoxiang12** [comment]
推测是没有装OpenGL。试试 sudo apt-get install libglew-dev freeglut3-dev

**Comment by liushuangliuliu** [comment]
升级到16.04没有问题了，14.04出现这个错误
