### ISSUE TITLE
请教一个问题。

### ISSUE THREAD

**Issue by jayoungo** [gaoxiang12/slambook#182]
第76页4.3.5节，推导SE(3)李代数导数的最后一步是如何去掉极限符号得到一个4*6矩阵的？
没有想明白，希望帮我解答一下。谢谢！

**Comment by gaoxiang12** [comment]
按照矩阵求导，向量对向量求导是一个矩阵。结果里左上角块是lim上半部分对\rho求导，右上角块是对\phi求导。按照极限运算，左上为3x3的单位阵，右上用SO3结论即可。

**Comment by jayoungo** [comment]
明白了。谢谢！
