### ISSUE TITLE
咨询openNI1.x版本以CMakeList.txt方式在程序中导入问题

### ISSUE THREAD

**Issue by menglitanhua** [gaoxiang12/slambook#19]
高博士，不好意思又要来打扰你了。
我在你ch9的project上修改了一下，打算用Kinect V1 测试运行VO那部分程序。安装的驱动组合为OpenNI1.5.7+Sensor5.1+nite1.5.2。在物理机中，openni的所有示例都能正常运行。在程序中我仿照其他库的书写方式，**include_directories("usr/include/ni"),以及target_link_liraries他的库，程序编译时总是提示一些文件不存在。。。而这个文件就在usr/include/ni下面。。**。不知道你有木有这么使用过，给我提供一些经验提示，网上能找到的都是OpenNI2+freenect的，改了改也不管什么用。 先谢谢了。

**Comment by gaoxiang12** [comment]
Kinect 1建议在ROS下使用，非ROS的情况我没有亲自测试过。祝好。
