### ISSUE TITLE
关于ch11中posee_graph_gtsam的问题

### ISSUE THREAD

**Issue by DYYYYYYYYY** [gaoxiang12/slambook#192]
请问这个程序需要的gtsam版本是什么呢，我用的3.2.1版本，但是这个编译会报错，感觉很多函数不存在。但是用4.0版本的gtsam又安装不上，每次cmake的时候都会出现这样的错误，不知道是怎么回事
-- Building 3rdparty
CMake Error at CMakeLists.txt:29 (gtsam_assign_source_folders):
  Unknown CMake command "gtsam_assign_source_folders".

**Comment by Milalaa** [comment]
@DYYYYYYYYY 你好！遇到了同样的问题，请问如何解决的呢？
