### ISSUE TITLE
第九讲中run_vo运行错误

### ISSUE THREAD

**Issue by tkdguraa** [gaoxiang12/slambook#225]
在第九讲project 0.2 测试过程中，运行bin/run_vo config/default.yaml之后会出现Segmentation fault,我断点发现问题处在myslam::VisualOdometry::Ptr vo ( new myslam::VisualOdometry )
这一部分，有人遇到相同的问题吗？

**Comment by skystalkerrc** [comment]
I have this trouble in ch13
