### ISSUE TITLE
pose_estimation_3d2d中的一个疑问

### ISSUE THREAD

**Issue by jingedawang** [gaoxiang12/slambook#24]
有一句代码理解不了，求高博答疑～

bundleAdjustment函数的最后一行
```
cout<<"T="<<endl<<Eigen::Isometry3d ( pose->estimate() ).matrix() <<endl;
```
`pose->estimate()`的返回值是`SE3Quat`，它怎么能作为参数传给`Eigen::Isometry3d`的构造函数呢？它们之间并没有继承关系呀？

**Comment by gaoxiang12** [comment]
只要存在类型转换关系即可，不必是继承关系。

**Comment by jingedawang** [comment]
@gaoxiang12 但是`Eigen::Isometry3d`的构造函数不接受`SE3Quat`类型的参数呀，哪来的转换呢？

**Comment by gaoxiang12** [comment]
SE3Quat有一个到Isometry3d的转换函数，检查一下这个类末尾几行代码。

**Comment by jingedawang** [comment]
哇塞，原来C++还有“类型转换运算符”这类东西，受教了，非常感谢！
