### ISSUE TITLE
关于第五章joinMap代码的几点疑问

### ISSUE THREAD

**Issue by FrankXue95** [gaoxiang12/slambook#25]
高博您好：最近学习您的SLAM14讲的过程中有一些疑问，是关于第五章JoinMap代码的。在这个代码中有两处我不是很理解：
第一处：代码的31行:for(auto& d:data)，不是很理解这里的取地址符&的作用是什么，感觉不加也没有什么问题。
第二处：代码的69行，根据公式应该是Pc=T*Pw,但是这里进行逆运算为什么是Pw=T*Pc，不是很理解。
麻烦高博百忙之中给予解答，谢谢！

**Comment by gaoxiang12** [comment]
您好，
1. &是取引用符，不加的话是传值。
2. T在读取的时候记录的是Twc，即相机到世界的变换。程序里Eigen::Vector3d point计算的是相机坐标系下坐标，在拼接地图里需要的是世界坐标，故有此转换。

**Comment by FrankXue95** [comment]
谢谢您的解答
