### ISSUE TITLE
直接法推导泰勒展开问题

### ISSUE THREAD

**Issue by lanfeiying** [gaoxiang12/slambook#274]
你好，我在读到直接法推导的时候对泰勒展开有点不理解。

原文如下：
![Screenshot from 2020-12-06 15-49-44](https://user-images.githubusercontent.com/22729258/101284957-b096c080-37da-11eb-88e9-438bf587fce5.png)

我查了查barfoot state estimation for robotics，里面对非线性函数的李代数扰动描述如下：
![Screenshot from 2020-12-06 15-55-40](https://user-images.githubusercontent.com/22729258/101285135-81348380-37db-11eb-8b5e-c6122b6fe799.png)
![Screenshot from 2020-12-06 15-57-04](https://user-images.githubusercontent.com/22729258/101285174-b2ad4f00-37db-11eb-841b-711f41ea7662.png)

我的理解是在barfoot的推导中没有使用链式法则。
我仿照一下对直接法的理解与推导如下：
![Screenshot from 2020-12-06 16-34-03](https://user-images.githubusercontent.com/22729258/101286155-de7f0380-37e0-11eb-94c8-1357b8627ba0.png)
上图中，泰勒展开的小量没有链式法则。

**Comment by lanfeiying** [comment]
我后来想到后面还是可以做一步链式法则， 用复合函数的泰勒展开做，小量是一个复合函数，后面再接着把对\delta\xi的一阶项保留，但是有点不同的是书中雅克比矩阵的第一项dI2 / du是对扰动前三维点的导数，而不是扰动后的三维点的导数，不知道这样理解是否可行

**Comment by GeoffreyHub** [comment]
说真的这里展开我也没看懂

**Comment by PengKunPROO** [comment]
而且你有没有发现在最后你写的推导公式的第三行，把exp(\delta \xi)展开之后，然后乘开，式子的意义变了，第一项代表P在像素中的坐标没问题，但是第二项代表的意思就很迷惑，按道理是把P转换到相机坐标系之后再乘以一个小的扰动，相当于求了P在像素坐标系的坐标的周围的坐标，那这第一项和第二项一加肯定不符合对P进行微小扰动的求导结果啊，所以对应的意义我没搞清楚，您能帮忙解答吗
