### ISSUE TITLE
对高翔博士“李代数与旋转矩阵的指数变换推导”质疑

### ISSUE THREAD

**Issue by JiangxinkeTao** [gaoxiang12/slambook#292]
![Screenshot from 2022-04-20 15-26-27](https://user-images.githubusercontent.com/42513042/164174096-a6f3e3d0-77af-4eae-942a-f567acb8f97a.png)

![Screenshot from 2022-04-20 15-26-41](https://user-images.githubusercontent.com/42513042/164174133-2d514c72-82a9-4d3c-bbf3-d71ef02cb6ba.png)

最后，诚盼您的回复，谢谢！

**Comment by gaoxiang12** [comment]
这个事情并不是讨论从t_0到t之间的过程，而是讨论t_0处的导数。你谈的是如何在t_0到任意t之间的积分，但书里想谈的是在t_0处对R求导。
类比于一个标量函数f(t)，它在t_0处的导数为f'(t_0)，泰勒展开为：
f(t) = f(t_0) + f'(t_0) dt + O(dt^2)
这件事情在t_0的邻域内都是有效的。

书里的李代数 \phi 实际是角速度的定义方式，因为有 dR/dt = \phi R，所以在短时间内有 R=exp(\phi t)。当然长时间内这个瞬时速度是在变化的，自然需要积分。离散的积分就是你上面写的那种连乘的形式，参考IMU积分方程即可。
<img width="763" alt="image" src="https://user-images.githubusercontent.com/6635511/164413560-60afb62f-0d57-4a42-aff5-7988579a7b49.png">

本节想介绍的只是\phi落在R(t_0)的切空间，以及切空间和流形之间的指数对数映射，积分这块倒没有太多介绍（因为没怎么提惯导）。

**Comment by JiangxinkeTao** [comment]
![Screenshot from 2022-04-23 10-49-47](https://user-images.githubusercontent.com/42513042/164869519-a043058d-8404-42d2-bf63-30df0f8784f6.png)
![Screenshot from 2022-04-23 10-49-56](https://user-images.githubusercontent.com/42513042/164869571-63c69134-a641-4b52-a5d5-20e212c312c3.png)

高博士，以上是我的看法，请您批评指正。

**Comment by gaoxiang12** [comment]
可以简化一下符号，一开始不用R(t)的写法，直接写dot(R)的公式。
<img width="771" alt="image" src="https://user-images.githubusercontent.com/6635511/164953659-76c05dbe-d089-4764-9bc3-be18ea165ffd.png">

**Comment by JiangxinkeTao** [comment]
好的，OK，现在清晰了，您现在使用的方法本质上就是上述的一次代数精度机械求积公式得到的结果，非常谢谢你！感谢！
