### ISSUE TITLE
第5章PCL软件源？

### ISSUE THREAD

**Issue by Xiaoli1127** [gaoxiang12/slambook#30]
W: 仓库 “http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu xenial Release” 没有 Release 文件。
N: 无法认证来自该源的数据，所以使用它会带来潜在风险。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 无法下载 http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

这是终端提示，安装PCL时提示的，应该是软件源没有更新吧？

**Comment by gaoxiang12** [comment]
请用apt-get update更新软件源即可。

**Comment by vincentbryan** [comment]
高博你好，我在安装PCL时出现
`E: Unable to locate package libpcl-all `
请问一下，有什么解决方法吗？
我尝试下载PCL源码进行编译，但是编译出现错误了
用的环境是ubuntu17.04

**Comment by vincentbryan** [comment]
已解决，改成ubuntu14.04便可

**Comment by davidishere** [comment]
改版本算解决了？
