### ISSUE TITLE
cs.h:No such file or diretory

### ISSUE THREAD

**Issue by Hansry** [gaoxiang12/slambook#33]
高老师你好，当我运行ch7/pose_estimation_3d2d.cpp时，其中include <g2o/solvers/csparse/linear_solver_csparse.h>，出现cs.h:No such file or diretory,自己尝试后发现解决不了，希望百忙中能抽空回复下我的问题，谢谢。

**Comment by gaoxiang12** [comment]
这需要引入csparse的头文件。你需要在CMakeLists.txt里加入find_package( xxx )之类的命令。
请自己尝试一下。

**Comment by Hansry** [comment]
It works ,thx

**Comment by cgbcgb** [comment]
i meet the same problem with you , how do you solve this problem ,can you share?@Hansry

**Comment by JianyiH** [comment]
I meet the same problem because I wrongly written the CSparse include_directories
