### ISSUE TITLE
ch4 page71 笔误

### ISSUE THREAD

**Issue by yuzhangliu** [gaoxiang12/slambook#42]
高博您好，
第四章71页最下边的图4-1，在三维变换中李代数那个block里面，最后的\zeta^{^}矩阵表达式右下角是否应该为1？

**Comment by BIRL-xu** [comment]
这个还就是0，如果是1，欧式变换矩阵T的右下角就是2了。



540852057@qq.com
 
发件人： yuzhangliu
发送时间： 2017-09-06 02:29
收件人： gaoxiang12/slambook
抄送： Subscribed
主题： [gaoxiang12/slambook] ch4 page71 笔误 (#42)
高博您好，
第四章71页最下边的图4-1，在三维变换中李代数那个block里面，最后的\zeta^{^}矩阵表达式右下角是否应该为1？
