### ISSUE TITLE
ch5点云拼接auto& d:data编译出错

### ISSUE THREAD

**Issue by ZzJiachenchen** [gaoxiang12/slambook#49]
有遇到如下编译报错的小伙伴么，还在学C++，学的不够多，不知如何改正，求指点，谢谢你们！
/home/zjc19941015/slambook/ch55/joinMap.cpp:31:12: error: ISO C++ forbids declaration of ‘d’ with no type [-fpermissive]
 for (auto& d:data)
            ^
/home/zjc19941015/slambook/ch55/joinMap.cpp:31:14: error: range-based ‘for’ loops are not allowed in C++98 mode
 for (auto& d:data)
              ^

**Comment by shaozu** [comment]
是不是编译的时候没有加支持c++11的选项。
试着在CMakeLists.txt中加上`set( CMAKE_CXX_FLAGS "-std=c++11 -O3" )`。

**Comment by ZzJiachenchen** [comment]
嗯嗯是的，第一次得到网友解答问题，哈哈哈谢谢小天使！
不过在CMake中加入您写出的一行代码报错，加的是同样功能的一句代码：
`add_compile_options(-std=c++11)`

**Comment by happyrookie** [comment]
for (auto& d:data)，楼主这个语句是什么意思呢？

**Comment by shaozu** [comment]
@happyrookie 参考 https://zh.cppreference.com/w/cpp/language/range-for
