### ISSUE TITLE
ch5 joinMap PCL installation

### ISSUE THREAD

**Issue by jamboo2017** [gaoxiang12/slambook#51]
按照书中写的步骤安装pcl的时候，收到如下提示：
ch5/joinMap/build$ sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
 This only exists for history reasons. Please use the PCL version included in Ubuntu:
sudo apt install libpcl-dev
于是我就cancel了，然后用sudo apt install libpcl-dev安装pcl。
安装完成后，$ cmake .. 的时候出现如下错误：
...
-- Checking for module 'libopenni2'
--   No package 'libopenni2' found
-- Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS)
** WARNING ** io features related to openni2 will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- looking for PCL_COMPONENT
-- Could NOT find PCL_COMPONENT (missing:  PCL_COMPONENT_LIBRARY PCL_COMPONENT_INCLUDE_DIR)
...
请问pcl能用Ubuntu1604的预编版吗？还是一定要按照书中的步骤安装？
谢谢。

**Comment by jamboo2017** [comment]
解决了。只要把openni2和proj lib装上就可以了。
sudo apt install libopenni2-dev
sudo apt install libproj-dev

**Comment by yuyangyg** [comment]
thanks
