### ISSUE TITLE
第五章的 imageBasics 可执行文件在运行时 报错

### ISSUE THREAD

**Issue by wowdeath** [gaoxiang12/slambook#64]
-pc:~/slambook/ch5/imageBasics/build$ ./imageBasics 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

**Comment by liushuangliuliu** [comment]
你好，我有同样的问题，请问你是怎么解决的？

**Comment by DesparadoW** [comment]
https://blog.csdn.net/xuesengxinyi/article/details/80932014
找了很久找到这篇博客，发现解决办法其实书还是视频里面已经提及过。主要是图片路径的问题
