### ISSUE TITLE
第9章0.4部分代码的问题

### ISSUE THREAD

**Issue by mantangL** [gaoxiang12/slambook#7]
第9章0.4代码中visual_odometry.cpp中checkEstimatedPose成员函数中T_r_c = ref_->T_c_w_ * T_c_w_estimated_.inverse();是不是应该写成T_r_c = T_c_w_estimated_*ref_->T_c_w_.inverse();
因为这里的T_c_w_estimated_相当于当前帧的T_c_w_，由于curr_->T_c_w_=T_r_c*ref_->T_c_w_
此式两端同时右乘ref_->T_c_w_.inverse()，即变为T_r_c = T_c_w_estimated_*ref_->T_c_w_.inverse();
是这样子来的吗？新手，如有不对的地方还请高博指点

**Comment by gaoxiang12** [comment]
谢谢，原文应该是正确的。TRC=TRW*TWC=TRW*TCW.inverse()，下标应该是连着的，照这样去理解就可以。

**Comment by mantangL** [comment]
谢谢您的回复，但是我仍有一点疑问，您这里所用的TRC的意思是从参考帧到当前帧所经过的变换矩阵吗？如果这样子的话TRW是指从参考帧所在相机坐标系到世界坐标系的变换矩阵，这与您原文中的ref_->T_c_w_是否就不一致了呢？按照您原文中的理解应该是表示从世界坐标系到相机坐标系的变换矩阵

**Comment by mantangL** [comment]
我想通了，高博，多谢！！！
