### ISSUE TITLE
P50 “rpy角旋转顺序是ZYX“  应该为XYZ吧？

### ISSUE THREAD

**Issue by ffgamelife** [gaoxiang12/slambook#70]
MRPT中用的是ypr 顺序是ZYX
ros中用rpy 顺序为XYZ

**Comment by ffgamelife** [comment]
查了下一般用ZYX顺序对应yaw pitch roll，
似乎没有固定的定义，不过书中建议改为ypr

**Comment by jafei0912** [comment]
你说的是对的，XYZ对应与姿态角所绕的旋转轴的方向，roll对应X，pitch对应Y，yaw对应Z。
