### ISSUE TITLE
Ch7: feature_extraction drawMatches and imshow issues

### ISSUE THREAD

**Issue by gh279760559** [gaoxiang12/slambook#87]
你好,
在尝试第七章feature 代码的时候发生如下问题:
![image](https://user-images.githubusercontent.com/20475927/36841660-e4cc90c6-1d40-11e8-8f70-a6e768f1ddfa.png)
无法显示matching points, 图片显示全黑.
已安装的opencv version = 3.3.1
following the link to install: https://www.learnopencv.com/install-opencv3-on-ubuntu/
谢谢

**Comment by gh279760559** [comment]
update: 尝试显示一张图没有任何问题
![image](https://user-images.githubusercontent.com/20475927/36841726-29e57c4a-1d41-11e8-8412-07bd7e0687ac.png)

**Comment by district10** [comment]
@gh279760559 同样问题, 把 imshow 窗口的 title 换成英文就好了...

**Comment by gh279760559** [comment]
@district10 多谢!

**Comment by cdlwhm1217096231** [comment]
@gh279760559 请问怎么运行这个程序？我的编译通过了，但是不知道怎么运行，谢谢！

**Comment by cdlwhm1217096231** [comment]
@district10 请问具体改哪里？谢谢！

**Comment by district10** [comment]
@cdlwhm1217096231 把中文字符串换成英文的, 这两行: <https://github.com/gaoxiang12/slambook/blob/master/ch7/feature_extraction.cpp#L79-L80>

**Comment by zhangxiaoya** [comment]
@gh279760559 你的系统是不是缺少中文语言包

**Comment by gh279760559** [comment]
@zhangxiaoya 应该是,我在国外,并且使用的ubuntu 16.04lts系统

**Comment by Krasaa** [comment]
@district10 多谢！

**Comment by shannon112** [comment]
感谢！ @district10
