### ISSUE TITLE
ch9 project 0.2 编译出错

### ISSUE THREAD

**Issue by wenb1234** [gaoxiang12/slambook#93]
read total 574 entries
Key frame size = 0
[ INFO:0] Initialize OpenCL runtime...
VO costs time: 0.012923
good matches: 12
pnp inliers: 8
reject because inlier is too small: 8
VO costs time: 0.02656
good matches: 7
pnp inliers: 0
reject because inlier is too small: 0
VO costs time: 0.03429
good matches: 8
pnp inliers: 0
reject because inlier is too small: 0
VO costs time: 0.025307
good matches: 4
pnp inliers: 4
reject because inlier is too small: 4
VO costs time: 0.013629
good matches: 3
OpenCV(3.4.1-dev) Error: Assertion failed (npoints >= 4 && npoints == std::max(ipoints.checkVector(2, 5), 

ipoints.checkVector(2, 6))) in solvePnPRansac, file /home/wenb1234/opencv/modules/calib3d/src/solvepnp.cpp, line 253
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) /home/wenb1234/opencv/modules/calib3d/src/solvepnp.cpp:253: error: (-215) Assertion failed: 

npoints >= 4 && npoints == std::max(ipoints.checkVector(2, 5), ipoints.checkVector(2, 6)) in function solvePnPRansac

Aborted (core dumped)

**Comment by gp1998-star** [comment]
请问你解决了吗？
